#pragma once

#define CONF_I2C_SLAVE_MODULE			SERCOM2

#define CONF_UART_MODULE				SERCOM1
#define CONF_UART_SERCOM_MUX_SETTING	USART_RX_1_TX_0_XCK_1
#define CONF_UART_SERCOM_PINMUX_PAD0	PINMUX_PA16C_SERCOM1_PAD0
#define CONF_UART_SERCOM_PINMUX_PAD1	PINMUX_PA17C_SERCOM1_PAD1
#define CONF_UART_SERCOM_PINMUX_PAD2	PINMUX_UNUSED
#define CONF_UART_SERCOM_PINMUX_PAD3	PINMUX_UNUSED

#define PWM_USE_TCC
#define PWM_MODULE						TC1
#define PWM_OUT_PIN						PIN_PA11E_TC1_WO1
#define PWM_OUT_MUX						MUX_PA11E_TC1_WO1
#define PWM_CHANNEL						TC_COMPARE_CAPTURE_CHANNEL_1

#define NUM_OF_COLS						5
#define NUM_OF_ROWS						7
#define NUM_OF_BTNS						0
