#pragma once

#define CONF_I2C_SLAVE_MODULE			SERCOM2

#define CONF_UART_MODULE				SERCOM1
#define CONF_UART_SERCOM_MUX_SETTING	USART_RX_1_TX_0_XCK_1
#define CONF_UART_SERCOM_PINMUX_PAD0	PINMUX_PA16C_SERCOM1_PAD0
#define CONF_UART_SERCOM_PINMUX_PAD1	PINMUX_PA17C_SERCOM1_PAD1
#define CONF_UART_SERCOM_PINMUX_PAD2	PINMUX_UNUSED
#define CONF_UART_SERCOM_PINMUX_PAD3	PINMUX_UNUSED

#define PWM_USE_TCC
#define PWM_MODULE						TC1
#define PWM_OUT_PIN						PIN_PA11E_TC1_WO1
#define PWM_OUT_MUX						MUX_PA11E_TC1_WO1
#define PWM_CHANNEL						TC_COMPARE_CAPTURE_CHANNEL_1

#define NUM_OF_COLS						5
#define NUM_OF_ROWS						7
#define NUM_OF_BTNS						0

#define BBQ10_LED_CAPSLOCK_PIN PIN_PA18
#define BBQ10_LED_NUMLOCK_PIN PIN_PA28

#define USB_DEVICE_VENDOR_ID	0x03EB
#define USB_DEVICE_PRODUCT_ID	0x0123

/* Enable USB VBUS detect */
//#define CONF_BOARD_USB_VBUS_DETECT  // no pin assign for VBUS detection

#define UDD_CLOCK_GEN      GCLK_GENERATOR_1
#define UDD_CLOCK_SOURCE   SYSTEM_CLOCK_SOURCE_DFLL

#define CONFIG_SLEEPMGR_ENABLE
